language: python
sudo: false
cache: pip

install: pip install tox
matrix:
  include:
    - python: 2.7
      env:
       - TOX_ENV=py27
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.6
      env:
        - TOX_ENV=py36
script: tox -e $TOX_ENV

notifications:
  email:
    - dmitry.viskov@webenterprise.ru
