version: '3'
services:
  game:
    restart: always
    container_name: pylti1p3
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./configs:/configs
      - ./game:/game
      - ../pylti1p3:/pylti1p3
    working_dir: /game
    ports:
      - "9001:9001"
